### ISSUE TITLE
support use other mirror

### ISSUE THREAD

**Issue by v6cc** [Bugswriter/pirokit#3]
In my country, can't access `https://1337x.to`, can access `https://1337x.is` (in browser, may be 5 seconds then redirect to 
`https://1337x.to` )

> (if I open a vpn service, both link worked)

but change  `baseurl="https://1337x.to"` to `baseurl="https://1337x.is"` not work, could you please support this site?

![redirect](https://user-images.githubusercontent.com/50515839/103871507-180c9c80-5108-11eb-8a33-8dc70ede4323.png)

**Comment by agent255** [comment]
There are thousand mirrors of 1337x, cant write code to support all
